import Carousel from "@/components/carousel"
import styles from '/styles/CarouselPage.module.css'
import Header from '@/components/header'
import Head from 'next/head'

export default function CarouselPage() {
    return(
        <>
            <Head>
                <title>Carousel Page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Header />
                <div className={styles.bodyContainer}>
                   <h1>Carousel</h1>
                   <Carousel />
                </div> 
            </main>
        </>
    )
}