import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Header from '@/components/header'
import SpinningEarth from '@/components/spinningEarth'
import styles from '/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet" /> 
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <div className={styles.bodyContent}>
          <SpinningEarth />
          <div className={styles.bodyLeft}>
            <div className={styles.bodyCopy}>
                <h2>Next.JS 13 Examples In Space!</h2>
                <p>Do you like useEffect and useState?<br /><br />
                  I made this page just for you!<br /><br />
                  Enjoy these fantastic useState and useEffect examples in SPACE!<br /><br />
                  Check out the examples by clicking any button below and remember to have FUN!<br /><br />
                  <b>WARNING: It is highly recommended to check useEffectOne out last!!!</b>
                </p>
            </div>
            <div className={styles.navLinks}>
                <Link href="/useEffectOne">useEffectOne</Link>
                <Link href="/useEffectTwo">useEffectTwo</Link>
                <Link href="/useEffectThree">useEffectThree</Link>
                <Link href="/carouselPage">Carousel</Link>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
