import Link from 'next/link'
import { useState, useEffect } from "react"
import styles from '/styles/UseEffectOne.module.css'
import Header from '@/components/header'
import Head from 'next/head'

export default function UseEffectOne() {

    const [number, setNumber] = useState(0);

    useEffect(() => {
        console.log(number);
        setNumber(number + 1);
    })

    return (
        <>
        <Head>
            <title>useEffectOne</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
            <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            <Header />
            <div className={styles.copyContainer}>
                <h1>WARNING!</h1>
                <p className={styles.subHead}>Infinite Loop Detected.</p>
                <p className={styles.bodyCopy}>Please refresh the page by clicking refresh.<br /><br /> If that won't work please try removing /useEffectOne from the URL and press enter.</p>
            </div>
            <div className={styles.counterContainer}>
                {number}
            </div>
        </main>
        </>
    )
}